# 실행 : docker-compose up -d
# 중지 : docker-compose down
version: "3"
services:
  mysql:
#    image: mysql:5.7 # 공식 mysql을 사용해도 되지만, 설정파일이 적용된(커스텀을 자동화할수있는) 이미지를 사용하기위해 별도 이미지를 사용한다.
    image: outsiderys/mysql:0.0.4
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: study
      MYSQL_USER: seolys
      MYSQL_PASSWORD: seolys!
      SPRING_PROFILE: dev # 실무에서 활용할때는 프로파일에 따라 환경변수 설정을 다르게 세팅해야 할것같다...
    # volumes: # 스터디라서 볼륨은 생략한다...
