# 실행 : docker-compose up -d
# 중지 : docker-compose down
version: "3"
services:
  spring-app:
    image: outsiderys/springboot-deploy-test:0.0.2
    ports:
      - 8080:8080
    environment:
      #      MYSQL_HOST: localhost # 개별 컨테이너로 띄웠을때 당연히 연결되지않음.
      MYSQL_HOST: host.docker.internal # [MacOS]컨테이너에서 호스트에 접근할때 사용.
      MYSQL_PORT: 3306
      MYSQL_DATABASE: study
      MYSQL_USER: seolys
      MYSQL_PASSWORD: seolys!