spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/study?useUnicode=yes&characterEncoding=UTF-8
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  devtools:
    livereload:
      enabled: true

logging:
  level:
    org.springframework: debug
    org.hibernate.SQL: debug
  #org.hibernate.type: trace